---
- name: Update package repositories
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Apache web server
  apt:
    name: apache2
    state: present

- name: Ensure Apache service is enabled and running
  service:
    name: apache2
    state: started
    enabled: yes
