---
- name: remove and uninstall mysql
  hosts: bdd
  vars:
    packages:
      - mysql-server
      - mariadb-server
  tasks:
    - name: uninstall mysql package
      apt:
        name: "{{ item }}"
        state: absent
      loop: "{{ packages }}"

    - name: remove mysql directory
      file: 
        path: "/var/lib/mysql"
        state: absent
    
    - name: remove mysql directory
      file: 
        path: "/etc/mysql"
        state: absent

    - name: remove cnf file
      file:
        path: "/root/.my.cnf"
        state: absent

    - name: reboot system
      reboot:
