---
- name: Preparation of a new linux server (Update packages, security, ...)
  hosts: Linux
  vars:
    - oldhostname: "{{ ansible_facts['ansible_nodename'] }}"
  vars_files:
    - passwd.yml
  vars_prompt:

    - name: hostname
      prompt: What name do you want to give to this server ?
      private: false

  tasks:
    - name: "Display hostname server"
      ansible.builtin.debug:
        msg: 'Server hostname is {{hostname}}!'

    - name: "Rename Hostname server"
      ansible.builtin.lineinfile:
        path: /etc/hostname
        regexp: 'oldhostname'
        line: "{{hostname}}"
    
    - name: "Reboot the server..."
      ansible.builtin.reboot:

    - name: "Import SSH role"
      import_role:
        name: 'ssh'

    - name: "Import User role"
      import_role:
        name: 'user'