---
- name: Install and configure a Wordpress website
  hosts: 'Webserver'
  vars_files:
    - secret.yml
  vars:
    - url_wp: "blog.example.com"
    - title_wp: "Example blog"
    - mail: "example@example.com"

  tasks:
    - name: "Update packages"
      import_role:
        name: 'update'
     
    - name: "Install and configure Lamp"
      import_role:
        name: 'lamp_setup'

    - name: "Creation of a basic user"
      user:
        name: wpadd
        comment: User for wp
        state: present

    - name: "Installation and configuration of wordpress"
      import_role:
        name: 'wp'


    

  post_tasks:
    - name : "Wordpress website installed and configured"
      debug:
        msg: 
          - "The wordpress website is launched"
