---
- name: Install and configure a Wordpress website
  hosts: 'localhost' 
  
  roles:
    - 'update'

  post_tasks:
    - name : "Wordpress website installed and configured"
      debug:
        msg: 
          - "The wordpress website is launched"