---
# tasks file for ssh
- name: Accept only passkey authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PasswordAuthentication'
    line: 'PasswordAuthentication yes'

- name: modify SSH port  
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#Port'
    line: 'Port 2298'

- name: Deny root login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PermitRootLogin'
    line: 'PermitRootLogin no'

- name: Allow specific user
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: AllowUsers nimda
    insertafter: EOF
  notify: Restart SSH