---
- name: add .my.cnf
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Set the root password
  mysql_user:
    name: root
    password: "{{ mysql_root_passwd }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: '*.*:ALL,GRANT'
    host: "{{ item }}"
    check_implicit_admin: true
    state: present
  with_items:
    - localhost
    - 127.0.0.1
    - ::1
  become: True