---
- name: create and configure a galera cluster
  hosts: galera_db_nodes
  become: yes
  vars_files:
    - vars/credentials.yml
    - vars.yml
  vars:
    - cluster_name: "galera_cluster"
    - bind_address: "0.0.0.0"
    - wsrep_cluster_address: "192.168.1.1,192.168.1.2,192.168.1.3"
    - sst_method: "rsync"
  roles:
    - os_prepare.yml

  tasks:
    - name: Add MariaDB repository
      apt_repository:
        repo: "deb [arch=amd64] http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu {{ ansible_distribution_release }} main"
        state: present

    - name: Import MariaDB public key
      apy_key:
        url: "https://mariadb.org/mariadb_release_signing_key.asc"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MariaDB and Cluster packages
      apt:
        name: "{{ item }}"
        state: latest
      loop: "{{ db_pkgs }}"

    - name: Stop MariaDB service
      systemd:
        name: mariadb
        state: stopped

    - name: Remove existing Mariadb
      file:
        path: "/etc/mysql/mariadb-conf.d/50-server.cnf"
        state: absent

    - name: Add new MariaDB configuration
      template:
        src: "50-server.cnf.j2"
        dest: "/etc/mysql/mariadb-conf.d/50-server.cnf"
      notify:
        - restart Mariadb

    - name: Bootstrap the Galera cluster on the first node
      shell: "galera_new_cluster"
      when: "'first_galera_node' in group_names"

handlers:
  - name: restart Mariadb
    systemd:
      name: mariadb
      state: restarted
    
