---
- name: test fact
  hosts: bdd
  tasks:
    - name: create
      set_fact: nodelist={%for host in groups['bdd']%}"{{hostvars[host].ansible_eth0.ipv4.address}}"{% if not loop.last %},{% endif %}{% endfor %}

    - debug: msg=[{{nodelist}}]

    - name: create file
      file:
        path: "test.cfg"
        state: touch

    - name: test file
      lineinfile:
        path: "test.cfg"
        line: "hosts: [{{ nodelist }}]"
