---
- name: Enable ufw
  community.general.ufw:
    state: enabled
    policy: allow

- name: Set logging
  community.general.ufw:
    logging: 'on'

- name: allow http port
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: 
    - '80'
    - '443'
    - '2298'
  
