---
- name: Install Laravel
  hosts: localhost
  vars_files:
    - vars.yml
  vars_prompt:
    - name: project_name
      prompt: What is the name of your Laravel's project?
      private: false
  roles:
    - ../roles/update
    
  
  tasks:
    - name: install required PHP packages
      apt:
        name: "{{ item }}"
        state: latest
      loop: "{{ php_pkts }}"

    - name: Download composer
      get_url: 
        url: https://getcomposer.org/installer
        dest: /tmp/composer-setup.php
        mode: '0755'

    - name: Install composer globally
      command: 
        cmd: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
        creates: /usr/local/bin/composer

    - name: Pause to confirm project name to create
      pause:
        prompt: "The Laravel project you're going to create is named {{ project_name }}. Do you want to proceed ? (yes/no)"
      register: project_confirm

    - name: debug project_confirm var
      ansible.builtin.debug:
        msg: "content of project_confirm var: {{ project_confirm }}"

    - name: set a variable based on the pause response
      set_fact:
        continue_install: "{{ 'yes' in project_confirm.user_input | lower }}"

    - name: stop execution if user did not confirm
      fail:
        msg: "You did not confirm, existing..."
      when: not confirm_install

    - name: Display information about the installation
      ansible.builtin.debug:
        msg:
        - "Laravel can be use by using the following command :"
        - "composer create-project --prefer-dist laravel/laravel project_name"
        - "To start a Laravel Development server :"
        - "cd project_name"
        - "php artisan serve"
      when: continue_install

      

  