---
- name: Install Laravel
  hosts: localhost
  vars_files:
    - vars.yml
    - credentials.yml
  vars_prompt:
    - name: project_name
      prompt: What is the name of your Laravel's project?
      private: false
    - name: work_env
      prompt: Is it for dev or prod environment? (dev/prod)
      private: false
  roles:
    - ../roles/update
    
  tasks:
    - name: install required PHP packages
      apt:
        name: "{{ item }}"
        state: latest
      loop: "{{ php_pkts }}"

    - name: Download composer
      get_url: 
        url: https://getcomposer.org/installer
        dest: /tmp/composer-setup.php
        mode: '0755'

    - name: Install composer globally
      command: 
        cmd: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
        creates: /usr/local/bin/composer

    - name: Pause to confirm project name to create
      pause:
        prompt: "The Laravel project you're going to create is named {{ project_name }}. Do you want to proceed ? (yes/no)"
      register: project_confirm

    - name: debug project_confirm var
      ansible.builtin.debug:
        msg: "content of project_confirm var: {{ project_confirm }}"

    - name: set a variable based on the pause response
      set_fact:
        confirm_install: "{{ 'yes' in project_confirm.user_input | lower }}"

    - name: stop execution if user did not confirm
      fail:
        msg: "You did not confirm, existing..."
      when: not confirm_install
    
    - name: Install Laravel Installer
      command:
        cmd: composer global require laravel/installer
        creates: /root/.composer/vendor/laravel/installer
    
    - name: Export Composer's bin directory to system PATH
      lineinfile:
        path: /etc/environment
        line: 'PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/root/.composer/vendor/bin"'

    - name: install LAMP stack for Prod environment
      ansible.builtin.include_role:
        name: ../roles/lamp_setup
      vars:
        app_name: "{{ project_name }}"
        path_app: "/var/www/{{ project_name }}"
        server_name: "{{ ansible_fqdn }}"
        server_admin: "root"
        mysql_root_passwd: "{{ mysql_passwd }}"
      when: confirm_install and work_env == "prod"

    - name: Create a new Laravel project
      command: composer create-project --prefer-dist laravel/laravel /var/www/{{project_name}}
      args:
        creates: /var/www/{{project_name}}
      when: confirm_install and work_env == "dev"
      register: install_ok

    - name: debug variable
      debug:
        msg: "{{ install_ok }}"

    - name: Display information about the installation
      ansible.builtin.debug:
        msg:
        - "The project {{project_name}} has been successfully install! "
        - "To start the Laravel Development server of the project, you have to execute the following commands :"
        - "cd /var/www/{{project_name}}"
        - "php artisan serve"
      when: install_ok

      

  