---
- name: Install Nginx package
  apt:
    name: nginx
    state: present

- name: Remove default Nginx site
  file:
    path: /etc/nginx/site-enabled/default
    state: absent

- name: Setup Nginx reverse proxy sites
  include_tasks: sites.yml
  loop: "{{ websites }}"
  loop_control:
    loop_var: item
      

- name: Reload Nginx to apply all changes
  service:
    name: nginx
    state: reloaded
