---

- name: update apt cache and upgrade packages
  apt:
    update_cache: yes
    upgrade: safe

- name: install specific packages
  apt:
    name: "{{ packages }}"
    state: latest

- name: 
