---
- name: Update package repositories
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install PHP packages
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ php_packages }}"
  when: php_packages is defined

- name: Change PHP.ini memory settings
  lineinfile:
    path: "/etc/php/{{ php_version }}/fpm/php.ini"
    line: "memory_limit = 512M"
    regexp: "^memory_limit ="
    backrefs: yes
  when: php_version is defined

- name: Check if PHP is installed.
  command: which php
  changed_when: false
  failed_when: false
  register: php_installed
