---
- hosts: esxi
  connection: local
  vars_files:
    - vars/vm-user.yml
  tasks:
  - include_vars : vars/vm-user.yml
  - name: Create a VM on a ESXi server
    community.vmware.vmware_guest:
      hostname : "{{ hostname }}"
      username : "{{ username }}"
      password : "{{ password }}"
      validate_certs: no
      folder: /
      name: VM_0001
      state: powered-off
      guest_id: centos64Guest
      disk:
      - size_gb: 10
        type: thin
        datastore: datastore1
      hardware:
        memory_mb: 1572
        num_cpus: 2
        scsi: paravirtual