---

- name: download wordpress files
  get_url:
    url: "https://wordpress.org/latest.zip"
    dest: "/tmp/wordpress_latest.zip"

# - name: create directory for wordpress  
#   file:
#     path: "{{ dir_wordpress }}"
#     state: directory
#     recurse: yes
#     owner: www-data
#     group: www-data
#     mode: 0644  

- name: install wordpress
  unarchive:
    src: "/tmp/wordpress_latest.zip"
    dest: "/var/www/"
    remote_src: true

- name: change repository's owner"
  file:
    path: "{{ dir_wordpress }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
    mode: 0775

- name: create apache configuration file
  template:
    src: wp.conf.j2
    dest: /etc/apache2/sites-available/wordpress.conf

- name: activate apache wordpress configuration
  shell: /usr/sbin/a2ensite wordpress
  notify: Restart apache

- name: Remove default apache file
  file:
    path: "//etc/apache2/sites-available/000-default.conf"
    state: absent

- name: create a database for wordpress
  mysql_db:
    name: "{{ db_name }}"
    login_user: "root"
    login_password: "{{ mysql_root_passwd }}"
    login_host: "localhost"
    state: present

- name: create a mysql user for wordpress
  mysql_user:
    name: "{{ mysql_user }}"
    login_user: "root"
    login_password: "{{ mysql_root_passwd }}"
    login_host: "localhost"
    password: "{{ mysql_wp_passwd }}"
    priv: 'wordpress.*:ALL,GRANT'
    state: present
  notify: Restart mysql

- name: generate admin passwd if wordpress_passwd is empty
  set_fact:
    wp_passwd: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=32') }}"
  when: wp_passwd == ''

- name: Restart Apache2 service
  service:
    name: apache2
    state: restarted